"""Writes the SwiftPM bootstrap package that Gradle cross-compiles for Android.

This is the Android counterpart of ``project_dist/xcode/Sources/*/main.swift``:
the process entry point is Swift, not C.  Android has no ``main()`` to hook —
the Activity is the entry point — so the bootstrap here is a *dynamic library*
whose exported Swift functions are called from Java through swift-java's
jextract JNI mode.  For that reason the bootstrap source is
``PythonBootstrap.swift`` and *must not* be named ``main.swift``: SwiftPM infers
target kind from that one filename, so a ``main.swift`` makes the target an
executable and the build fails with "library product 'NucleantMain' should not
contain executable targets".  Gradle builds it with ``swift build --swift-sdk <triple>``
(the pattern from swiftlang/swift-android-examples) and drops the resulting
``.so`` files, plus the Swift runtime, into ``jniLibs/<abi>/``.

Nothing in here is hand-written JNI: the Java -> Swift direction is generated by
``JExtractSwiftPlugin``, and the Swift -> Android direction belongs to
NucleantApplication, which uses swift-java's ``@JavaClass`` wrappers.  The one
C module that remains is ``CAndroidNativeWindow`` — a module map over the NDK's
``android/native_window_jni.h``, because turning a ``android.view.Surface`` into
the ``ANativeWindow*`` that ``VK_KHR_android_surface`` wants is a C API with no
Java equivalent.

**This package does not depend on NucleantApplication, NucleantVulkan, or
anything else in the Nucleant stack**, and must not.  Those are built for
Android the same way they are for Linux and macOS — as part of the ``nucleant``
wheel, by pyswiftkit-builder under cibuildwheel — and reach the APK as
``site_packages/<abi>/.libs/<abi>/*.so``, which Gradle copies into jniLibs.
Building them a second time from here would put two copies of every Swift
library into the same APK — the exact hazard PyNucleantUI's pyproject already
documents for the Swift runtime on Linux.  What crosses between the two is a
dlsym'd C ABI (see ``AndroidSurface.swift``): the bootstrap owns the JNI edge
and the window, and looks up hooks the wheel exports.
"""

from __future__ import annotations

from pathlib import Path

# swift-java release that introduced the `SwiftJava` product name (the module
# formerly known as JavaKit) and jextract's `"mode": "jni"` config.
SWIFT_JAVA_VERSION = "0.1.2"

# Name of the SwiftPM package directory inside the app module, and of its one
# library target.  The directory name is load-bearing: JExtractSwiftPlugin
# writes its generated Java under
#   .build/plugins/outputs/<package-dir-lowercased>/<target>/destination/...
# and app/build.gradle.kts points a Java srcDir at exactly that path.
SWIFT_PACKAGE_DIR = "swift"
SWIFT_TARGET_NAME = "NucleantMain"

# The Java package jextract emits into, and the one the app's Java imports.
#
# Fixed, never derived from the app's applicationId — the same way SDL's Java is
# always org.libsdl.app whatever app it is embedded in. The package name lands in
# the generated class *and* in every JNI symbol
# (Java_org_nucleantui_NucleantMain_...), so deriving it from the applicationId
# would give every app a differently-named bridge and make a prebuilt bootstrap
# impossible to share.
JAVA_PACKAGE = "org.nucleantui"

# Module wrapping the CPython C API. Its own name, not "CPython", so it can
# never be confused with the CPython *package* — that one is built in PIP_MODE
# for extension modules loaded into a running interpreter, and deliberately
# does not link libpython. The bootstrap has to start the interpreter, so it
# links libpython3.so out of jniLibs.
PYTHON_MODULE_NAME = "CPythonBootstrap"

# Per-ABI Python headers live here; Gradle points -Xcc -I at the right one for
# the triple it is currently building.
PYTHON_INCLUDE_DIR = "python_include"


def write_swift_package(
    swift_dir: Path,
    package_name: str,
    app_module: str,
    python_version: str,
) -> None:
    """Materialize the whole bootstrap package under ``swift_dir``."""
    target_dir = swift_dir / "Sources" / SWIFT_TARGET_NAME
    window_dir = swift_dir / "Sources" / "CAndroidNativeWindow"
    python_dir = swift_dir / "Sources" / PYTHON_MODULE_NAME
    for d in (target_dir, window_dir, python_dir):
        d.mkdir(parents=True, exist_ok=True)

    _write_package_swift(swift_dir)
    _write_swift_java_config(target_dir)
    _write_native_window_shim(window_dir)
    _write_python_shim(python_dir)
    _write_python_bootstrap_swift(target_dir, app_module, python_version)
    _write_surface_swift(target_dir)


# ---------------------------------------------------------------------------
# Package.swift
# ---------------------------------------------------------------------------


def _write_package_swift(swift_dir: Path) -> None:
    """Emit Package.swift.

    swift-java is the only external dependency.  Nothing from the Nucleant
    stack appears here — see the module docstring for why.
    """
    content = f"""\
// swift-tools-version: 6.2
//
// Android bootstrap package — generated by ksproject.  Built by Gradle, once
// per ABI, via `swift build --swift-sdk <triple>`; the product lands in
// jniLibs/<abi>/ and the jextract-generated Java lands in the app's java
// source set.  Treat it as generated output — regenerating overwrites it.
//
// Scope is deliberately tiny: start the interpreter, own the JNI edge, hand
// the surface over.  NucleantApplication and the rest of the stack are NOT
// dependencies — they ship inside the `nucleant` wheel (built by
// pyswiftkit-builder, same as on Linux and macOS) and Gradle copies them from
// site_packages/<abi>/.libs into jniLibs. Depending on them here would build
// and package a second copy of every one of those libraries.

import PackageDescription

let package = Package(
    name: "{SWIFT_TARGET_NAME}",
    products: [
        // .dynamic: Gradle copies the built lib{SWIFT_TARGET_NAME}.so straight into
        // jniLibs/<abi>/, and the JNI shim jextract generates is compiled into
        // it — a static product would have nothing to load at runtime.
        .library(
            name: "{SWIFT_TARGET_NAME}",
            type: .dynamic,
            targets: ["{SWIFT_TARGET_NAME}"]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/swiftlang/swift-java", from: "{SWIFT_JAVA_VERSION}")
    ],
    targets: [
        // The NDK's android/native_window_jni.h.  ANativeWindow_fromSurface is
        // the only way to get from a android.view.Surface to the handle
        // VK_KHR_android_surface needs, and it has no Java-side equivalent, so
        // it cannot go through swift-java like everything else does.
        .systemLibrary(name: "CAndroidNativeWindow"),
        // The CPython C API. Headers are per-ABI (pyconfig.h differs), so the
        // include path is passed by Gradle at build time as
        // `-Xcc -I<pkg>/{PYTHON_INCLUDE_DIR}/<abi>` rather than baked in here.
        .systemLibrary(name: "{PYTHON_MODULE_NAME}"),
        .target(
            name: "{SWIFT_TARGET_NAME}",
            dependencies: [
                "CAndroidNativeWindow",
                "{PYTHON_MODULE_NAME}",
                .product(name: "SwiftJava", package: "swift-java")
            ],
            swiftSettings: [
                .swiftLanguageMode(.v5)
            ],
            plugins: [
                // Generates the Java class the Activity calls, plus the JNI
                // glue that lands in lib{SWIFT_TARGET_NAME}.so.  Configured by
                // Sources/{SWIFT_TARGET_NAME}/swift-java.config.
                .plugin(name: "JExtractSwiftPlugin", package: "swift-java")
            ]
        )
    ]
)
"""
    (swift_dir / "Package.swift").write_text(content, encoding="utf-8")


def _write_python_shim(shim_dir: Path) -> None:
    """Module map over ``Python.h``.

    No absolute path here on purpose: ``<Python.h>`` resolves from the
    ``-Xcc -I`` Gradle passes for the ABI being built, so one module serves
    every architecture despite their differing ``pyconfig.h``.
    """
    (shim_dir / "shim.h").write_text(
        """\
#pragma once

#define PY_SSIZE_T_CLEAN
#include <Python.h>
""",
        encoding="utf-8",
    )
    (shim_dir / "module.modulemap").write_text(
        f"""\
module {PYTHON_MODULE_NAME} [system] {{
    header "shim.h"
    // libpython3.so is staged into jniLibs by the generator before Gradle
    // runs, and Gradle passes that directory as the link search path. The
    // bootstrap *starts* the interpreter, so unlike an extension module it
    // links libpython for real rather than resolving against an already
    // loaded one.
    link "python3"
    export *
}}
""",
        encoding="utf-8",
    )


def _write_swift_java_config(target_dir: Path) -> None:
    """jextract's per-target config: which Java package to emit into, and JNI
    mode (rather than the FFM mode, which Android's JVM does not have).

    The package is ``JAVA_PACKAGE``, not the app's — see the constant.
    """
    content = f"""\
{{
  "javaPackage": "{JAVA_PACKAGE}",
  "mode": "jni"
}}
"""
    (target_dir / "swift-java.config").write_text(content, encoding="utf-8")


def _write_native_window_shim(shim_dir: Path) -> None:
    (shim_dir / "shim.h").write_text(
        """\
#pragma once

// ANativeWindow_fromSurface + the ANativeWindow accessors.  Pulled in through
// a module map rather than a compiled target: these are NDK headers, already
// present in the Swift Android SDK's sysroot, and libandroid.so is linked
// below.
#include <android/native_window.h>
#include <android/native_window_jni.h>
""",
        encoding="utf-8",
    )
    (shim_dir / "module.modulemap").write_text(
        """\
module CAndroidNativeWindow [system] {
    header "shim.h"
    link "android"
    export *
}
""",
        encoding="utf-8",
    )


# ---------------------------------------------------------------------------
# PythonBootstrap.swift — the Python bootstrap
#
# Not "main.swift": SwiftPM treats that filename as top-level code and infers an
# executable target from it, which a `.library` product may not contain.
# ---------------------------------------------------------------------------


def _write_python_bootstrap_swift(
    target_dir: Path, app_module: str, python_version: str
) -> None:
    """The Android analogue of Sources/Shared/NucleantLauncher.swift.

    Same phase order, same isolated-config startup, same
    ``runpy._run_module_as_main`` entry point — see the header comment in the
    emitted file for what the platform forces to differ.  Every ``public func``
    becomes a static method on the jextract-generated Java class
    ``org.nucleantui.NucleantMain``, which is what MainActivity and
    NucleantService call; everything else is internal so it stays out of the
    generated Java.
    """
    content = (
        _PYTHON_BOOTSTRAP_SWIFT.replace("{{ app_module }}", app_module)
        .replace("{{ python_version }}", python_version)
        .replace("{{ python_module }}", PYTHON_MODULE_NAME)
    )
    (target_dir / "PythonBootstrap.swift").write_text(content, encoding="utf-8")
    # A main.swift left over from an earlier generation would still be picked up
    # as top-level code and re-break the library product.
    (target_dir / "main.swift").unlink(missing_ok=True)


# A plain template, not an f-string: Swift is nothing but braces, and doubling
# every one of them to survive `str.format` is how the previous version of this
# file grew unreadable.
_PYTHON_BOOTSTRAP_SWIFT = """\
//
//  PythonBootstrap.swift
//  Android bootstrap — generated by ksproject.
//
//  The Android half of xcode/Sources/Shared/NucleantLauncher.swift, and
//  deliberately the same shape: one launcher object, the same phase order
//  (preLaunch -> initPython -> onLaunch -> onExit), the same isolated
//  PyPreConfig/PyConfig startup, and `runpy._run_module_as_main` as the entry
//  point — so an app's __main__.py is reached the same way on every platform.
//
//  Two hard constraints shape what can be written here, and they are why the
//  Apple launcher looks the way it does as well:
//
//  * No C variadics.  Swift cannot import them, so `Py_BuildValue`,
//    `PyTuple_Pack` and every other `...` function is marked unavailable.
//    Arguments therefore go through `PyUnicode_FromString` +
//    `PyObject_CallOneArg`, and the module is run via the one-argument
//    `runpy._run_module_as_main(name)` rather than the public
//    `runpy.run_module(name, run_name:, alter_sys:)`, whose keywords would need
//    a dict built by `Py_BuildValue`.
//  * Not named main.swift.  SwiftPM reads that one filename as top-level code
//    and makes the target an executable, which the `.dynamic` library product
//    in Package.swift cannot contain.  There is no process entry point here:
//    the Activity is it, and the `public func`s at the bottom are what
//    swift-java's jextract exports to Java (JNI mode; see swift-java.config).
//
//  What differs from the Apple launcher is only what the platform forces:
//    * paths come from the Activity (its `filesDir/app`), not Bundle.main
//    * the tree is unzipped at runtime, so preLaunch waits for the unpack marker
//    * the app module does not run until a Surface exists — the same rule as
//      iOS not starting Python before a UIWindowScene has connected
//    * stdout/stderr go nowhere on Android, so both are rebound to logcat
//

import Android
import {{ python_module }}
import Foundation

// MARK: - Logging

/// NSLog, not print: Android hands the process no usable stdout, so print()
/// output is discarded before anyone can read it.  Python's own streams get the
/// same treatment in `redirectStdio()`.
func nucleantLog(_ message: String) {
    NSLog("[nucleant] \\(message)")
}

/// `__android_log_write` reached through dlsym, the same way the rest of the
/// file reaches host hooks — liblog is always loaded in an app process, and
/// this avoids adding a header and a `link` to the C shim for one function.
private let androidLogWrite: (@convention(c) (Int32, UnsafePointer<CChar>?, UnsafePointer<CChar>?) -> Int32)? = {
    guard
        let handle = dlopen("liblog.so", RTLD_NOW),
        let sym = dlsym(handle, "__android_log_write")
    else { return nil }
    return unsafeBitCast(
        sym,
        to: (@convention(c) (Int32, UnsafePointer<CChar>?, UnsafePointer<CChar>?) -> Int32).self
    )
}()

/// Straight to logcat, never through NSLog.  This is called from the thread
/// draining the redirected fds, and on Android NSLog itself writes to stderr —
/// which is one end of that pipe, so using it here would feed every line back
/// into the reader and spin forever.
private func nucleantLogRaw(_ line: String) {
    line.withCString { text in
        "python".withCString { tag in
            _ = androidLogWrite?(6 /* ANDROID_LOG_ERROR */, tag, text)
        }
    }
}

/// fd-level backstop for `redirectStdio()`.  That one rebinds `sys.stdout` /
/// `sys.stderr`, so it only catches writes that go through those objects and
/// only once the interpreter is up — it misses `PyErr_Print()` before
/// `redirectStdio()` runs, faulthandler, and anything a C extension writes to
/// fd 2 directly.  Those are exactly the writes that carry a startup
/// traceback, so both fds are rebound here to a pipe drained by a thread that
/// forwards each line to logcat.
func nucleantRedirectFDs() {
    var fds: [Int32] = [0, 0]
    guard pipe(&fds) == 0 else {
        nucleantLog("ERROR: pipe() failed — stdout/stderr not captured")
        return
    }
    dup2(fds[1], STDOUT_FILENO)
    dup2(fds[1], STDERR_FILENO)
    close(fds[1])
    setvbuf(stdout, nil, _IOLBF, 0)
    setvbuf(stderr, nil, _IONBF, 0)

    let readFD = fds[0]
    let reader = Thread {
        var chunk = [UInt8](repeating: 0, count: 4096)
        var pending = ""
        while true {
            let n = read(readFD, &chunk, chunk.count)
            if n <= 0 { break }
            pending += String(decoding: chunk[0..<n], as: UTF8.self)
            while let nl = pending.firstIndex(of: "\\n") {
                nucleantLogRaw(String(pending[pending.startIndex..<nl]))
                pending = String(pending[pending.index(after: nl)...])
            }
        }
        if !pending.isEmpty { nucleantLogRaw(pending) }
    }
    reader.stackSize = 512 * 1024
    reader.start()
}

struct LaunchError: Error, CustomStringConvertible {
    let description: String
    init(_ description: String) { self.description = description }
}

// MARK: - Entry point

/// `runpy._run_module_as_main(name)` — the same call the Apple launcher makes.
///
/// The private `_run_module_as_main` rather than the public `run_module`
/// because it takes the module name as its only required argument: keywords
/// would need `Py_BuildValue`, which Swift cannot call.
func run_module_as_main(_ name: String) -> Int32 {

    guard
        let run_py = "runpy".withCString(PyImport_ImportModule),
        let run_fn = "_run_module_as_main".withCString({ PyObject_GetAttrString(run_py, $0) }),
        let module = name.withCString(PyUnicode_FromString)
    else {
        PyErr_Print()
        return -1
    }

    defer {
        Py_DecRef(module)
        Py_DecRef(run_fn)
        Py_DecRef(run_py)
    }

    nucleantLog("running module: \\(name)")

    guard let result = PyObject_CallOneArg(run_fn, module) else {
        PyErr_Print()
        return -1
    }

    Py_DecRef(result)

    return 1
}

func PyStatus_Exception(_ status: PyStatus) -> Bool {
    {{ python_module }}.PyStatus_Exception(status) == 1
}

extension PyStatus {
    var error: String { err_msg.map { String(cString: $0) } ?? "(no message)" }
}

// MARK: - Launcher

final class NucleantLauncher {

    nonisolated(unsafe) static let shared = NucleantLauncher()

    var env: Environment = .init()

    /// Where MainActivity unpacked assets.zip — its `filesDir/app`.  Java
    /// passes it to every entry point; the env var is the fallback for a
    /// service process started without one.
    var appPath: String = ProcessInfo.processInfo.environment["ANDROID_APP_PATH"] ?? ""

    /// The app's importable module name, baked in from pyproject's
    /// `project.name`.  `nucleantSetAppModule` overrides it; the Apple side
    /// reads the same value from Info.plist's AppModule key.
    var appModule: String = "{{ app_module }}"

    let pythonVersion = "{{ python_version }}"

    /// How long to wait for the first Surface before running the app module
    /// regardless.  A surface that never arrives is a bug to see in logcat, not
    /// a state to hang in.
    let surfaceTimeout: TimeInterval = 10

    // The layout MainActivity's unpack produces, ABI-flattened:
    //   <appPath>/python{{ python_version }}/             pure-Python stdlib
    //   <appPath>/python{{ python_version }}/lib-dynload  this ABI's extension modules
    //   <appPath>/site-packages/           the wheels
    //   <appPath>/                         the app's own modules
    var stdlibPath: String { "\\(appPath)/python\\(pythonVersion)" }
    var dynloadPath: String { "\\(stdlibPath)/lib-dynload" }
    var sitePackagesPath: String { "\\(appPath)/site-packages" }

    // MARK: Phases

    func setup() {
        androidSettings()
    }

    /// The Android counterpart of the Apple launcher's `kivySettings()`.
    /// MainActivity already exported the ANDROID_* variables the app tree uses
    /// to find itself before the first Swift call ran; what is left is what
    /// CPython itself reads.
    private func androidSettings() {
        env.LC_CTYPE = "UTF-8"
        env.PYTHONNOUSERSITE = "1"
        env.PYTHONUNBUFFERED = "1"
    }

    func preLaunch(_ on_pre_launch: () -> Void) throws {
        nucleantRedirectFDs()
        androidSettings()
        awaitUnpack()
        if chdir(appPath) != 0 {
            nucleantLog("ERROR: chdir(\\(appPath)) failed")
        }
        on_pre_launch()
    }

    func onLaunch() throws -> Int32 {
        try onLaunch(appModule, waitForSurface: true)
    }

    /// `waitForSurface` is the Android form of the rule the iOS launcher
    /// implements with KivySceneDelegate: the app module is what constructs the
    /// window, and it must not run before there is a real one to build on.
    /// Service processes are headless, so they pass false.
    func onLaunch(_ module: String, waitForSurface: Bool) throws -> Int32 {
        if waitForSurface, !nucleantAwaitSurface(timeout: surfaceTimeout) {
            nucleantLog("no surface after \\(Int(surfaceTimeout))s — starting anyway")
        }
        return run_module_as_main(module)
    }

    func onExit() throws {
        _ = Py_FinalizeEx()
    }

    func crash_dialog(_ details: String) {
        nucleantLog("Application has crashed!")
        nucleantLog("========================\\n\\(details)")
    }

    /// The tree is unzipped by a thread MainActivity starts, and
    /// `.unpack_done` is written last — so its presence means the tree is
    /// complete.  Nothing can be imported before it exists.
    private func awaitUnpack() {
        let marker = "\\(appPath)/.unpack_done"
        if FileManager.default.fileExists(atPath: marker) { return }
        nucleantLog("waiting for asset unpack")
        while !FileManager.default.fileExists(atPath: marker) {
            usleep(50_000)
        }
        nucleantLog("assets unpacked")
    }
}

// MARK: - Interpreter startup

extension NucleantLauncher {

    /// The Apple launcher's `run(...)` without argc/argv — there is no command
    /// line — and returning the status rather than ending the process: Java
    /// owns the process, and MainActivity finishes the Activity on this value.
    static func run(
        module: String,
        waitForSurface: Bool,
        on_pre_launch: () -> Void = {},
        on_preimport: () -> Void = {},
        on_quit: (Int32) -> Void = { _ in }
    ) -> Int32 {
        let cls = Self.shared
        var status: Int32 = 0
        do {
            try cls.preLaunch(on_pre_launch)
            try cls.initPython(on_preimport: on_preimport)
            let result = try cls.onLaunch(module, waitForSurface: waitForSurface)
            // run_module_as_main reports the Apple launcher's values: 1 for a
            // clean run, -1 if the entry point raised.  Java wants a
            // process-style code.
            status = result < 0 ? 1 : 0
            try cls.onExit()
        } catch {
            cls.crash_dialog("\\(error)")
            status = 1
        }
        nucleantLog("python exit \\(status)")
        on_quit(status)
        return status
    }

    func initPython(on_preimport: () -> Void) throws {

        var preconfig = PyPreConfig()
        var config = PyConfig()

        var status: PyStatus

        nucleantLog("configuring isolated Python \\(pythonVersion) in \\(appPath)")
        PyPreConfig_InitIsolatedConfig(&preconfig)
        PyConfig_InitIsolatedConfig(&config)

        preconfig.utf8_mode = 1

        config.buffered_stdio = 0
        config.write_bytecode = 0
        config.module_search_paths_set = 1
        config.install_signal_handlers = 0
        // An isolated config ignores the environment, but MainActivity's
        // ANDROID_* exports are how the app tree locates itself.
        config.use_environment = 1

        setenv("LC_CTYPE", "UTF-8", 1)

        nucleantLog("pre-initializing Python runtime")
        status = Py_PreInitialize(&preconfig)
        if PyStatus_Exception(status) {
            PyConfig_Clear(&config)
            throw LaunchError("Unable to pre-initialize Python interpreter: \\(status.error)")
        }

        // PYTHONHOME.  The unpacked tree is its own prefix; there is no system
        // Python on the device to fall back to.
        nucleantLog("PythonHome: \\(appPath)")
        if let wtmp_str = Py_DecodeLocale(appPath, nil) {
            var config_home = config.home
            status = PyConfig_SetString(&config, &config_home, wtmp_str)
            config.home = config_home
            PyMem_RawFree(wtmp_str)
            if PyStatus_Exception(status) {
                PyConfig_Clear(&config)
                throw LaunchError("Unable to set PYTHONHOME: \\(status.error)")
            }
        }

        status = PyConfig_Read(&config)
        if PyStatus_Exception(status) {
            PyConfig_Clear(&config)
            throw LaunchError("Unable to read site config: \\(status.error)")
        }

        // sys.path, in resolution order.  ANDROID_NATIVE_LIB_DIR comes last:
        // modules whose .so ships in jniLibs resolve there without a second
        // copy inside the unpacked tree.  site-packages is deliberately absent
        // — it is added below, through site.addsitedir.
        var searchPaths = [stdlibPath, dynloadPath, appPath]
        if let nativeLibDir = ProcessInfo.processInfo.environment["ANDROID_NATIVE_LIB_DIR"] {
            searchPaths.append(nativeLibDir)
        }

        nucleantLog("PYTHONPATH:")
        for path in searchPaths {
            nucleantLog(" - \\(path)")
            guard let wtmp_str = Py_DecodeLocale(path, nil) else {
                PyConfig_Clear(&config)
                throw LaunchError("Could not decode search path \\(path)")
            }
            status = PyWideStringList_Append(&config.module_search_paths, wtmp_str)
            PyMem_RawFree(wtmp_str)
            if PyStatus_Exception(status) {
                PyConfig_Clear(&config)
                throw LaunchError("Unable to add \\(path) to sys.path: \\(status.error)")
            }
        }

        on_preimport()

        nucleantLog("initializing Python runtime")
        status = Py_InitializeFromConfig(&config)
        PyConfig_Clear(&config)
        if PyStatus_Exception(status) {
            throw LaunchError("Unable to initialize Python interpreter: \\(status.error)")
        }

        // Before addsitedir, so a failure inside a .pth file is reportable.
        redirectStdio()
        try addSiteDir(sitePackagesPath)

        nucleantLog("---------------------------------------------------------------------------")
    }

    /// `site.addsitedir(path)` rather than a fourth sys.path entry, for the
    /// same reason the Apple launcher does it: .pth files in site-packages have
    /// to be executed, and only addsitedir does that.
    private func addSiteDir(_ path: String) throws {
        guard FileManager.default.fileExists(atPath: path) else {
            nucleantLog("no site-packages at \\(path) — skipping")
            return
        }

        guard let module = PyImport_ImportModule("site") else {
            PyErr_Print()
            throw LaunchError("Could not import site module")
        }
        defer { Py_DecRef(module) }

        guard
            let module_attr = PyObject_GetAttrString(module, "addsitedir"),
            PyCallable_Check(module_attr) == 1
        else {
            PyErr_Print()
            throw LaunchError("Could not access site.addsitedir")
        }
        defer { Py_DecRef(module_attr) }

        guard let app_packages_path = PyUnicode_FromString(path) else {
            throw LaunchError("Could not convert \\(path) to a Python string")
        }
        defer { Py_DecRef(app_packages_path) }

        nucleantLog("adding site directory: \\(path)")
        guard let result = PyObject_CallOneArg(module_attr, app_packages_path) else {
            PyErr_Print()
            throw LaunchError("Could not add \\(path) using site.addsitedir")
        }
        Py_DecRef(result)
    }

    /// Routes `sys.stdout` / `sys.stderr` into logcat.  The Apple launcher only
    /// has to unbuffer them (`config.buffered_stdio = 0`, above) because Xcode
    /// reads the process's real streams; on Android nothing does.
    private func redirectStdio() {
        // liblog.so through ctypes rather than an extension module: Android's
        // logging entry point is plain C, always loaded in the process, and
        // this keeps a Swift-side Python module out of the bootstrap just to
        // print.  PyRun_SimpleString is not variadic, so it is callable here.
        _ = PyRun_SimpleString(\"\"\"
import ctypes
import sys

_ANDROID_LOG_INFO = 4
_ANDROID_LOG_ERROR = 6
_liblog = ctypes.CDLL('liblog.so')
# getattr, not attribute access: inside a class body Python mangles any
# identifier starting with two underscores, so `_liblog.__android_log_write`
# becomes a lookup for `_LogcatStream__android_log_write` and always fails.
_log_write = getattr(_liblog, '__android_log_write')


class _LogcatStream:
    def __init__(self, priority):
        self._priority = priority
        self._buffer = ''

    def write(self, text):
        self._buffer += text
        while '\\\\n' in self._buffer:
            line, _, self._buffer = self._buffer.partition('\\\\n')
            _log_write(
                self._priority, b'python', line.encode('utf-8', 'replace')
            )
        return len(text)

    def flush(self):
        if self._buffer:
            _log_write(
                self._priority, b'python', self._buffer.encode('utf-8', 'replace')
            )
            self._buffer = ''

    def isatty(self):
        return False


sys.stdout = _LogcatStream(_ANDROID_LOG_INFO)
sys.stderr = _LogcatStream(_ANDROID_LOG_ERROR)
\"\"\")
    }
}

// MARK: - Java-facing entry points
//
// jextract turns each of these into a static method on
// org.nucleantui.NucleantMain, the class MainActivity and NucleantService
// call.  They are the only public declarations in the file; everything above is
// internal so it stays out of the generated Java.

/// Overrides the app module baked in at generation time.
public func nucleantSetAppModule(_ module: String) {
    NucleantLauncher.shared.appModule = module
}

/// Boots CPython against the unpacked asset tree and runs the app module.
///
/// Called from the Activity's Python thread, never the UI thread: it does not
/// return until the app exits.  `appPath` is the directory MainActivity
/// unpacked assets.zip into (its `filesDir/app`).
///
/// Returns 0 on a clean exit, 1 if the interpreter failed to start or the entry
/// point raised.
public func nucleantRunPython(appPath: String) -> Int32 {
    let launcher = NucleantLauncher.shared
    launcher.appPath = appPath
    return NucleantLauncher.run(module: launcher.appModule, waitForSurface: true)
}

/// Boots CPython and runs a service entry point, headless.
///
/// Services run in their own process (`android:process=":name"` in the
/// manifest), so this gets a fresh interpreter with no surface behind it and no
/// relationship to the Activity's — which is why it does not wait for one.
public func nucleantRunService(appPath: String, entrypoint: String) -> Int32 {
    NucleantLauncher.shared.appPath = appPath
    return NucleantLauncher.run(module: entrypoint, waitForSurface: false)
}

// MARK: - Environment

extension NucleantLauncher {
    @dynamicMemberLookup
    struct Environment {

        subscript(dynamicMember key: String) -> String? {
            get {
                if let result = key.withCString(getenv) {
                    return .init(cString: result)
                }
                return nil
            }
            set {
                // setenv wants a non-optional: Swift's implicit
                // String -> UnsafePointer<CChar> bridge does not cover String?.
                _ = key.withCString { _key in
                    guard let newValue else { return unsetenv(_key) }
                    return setenv(_key, newValue, 1)
                }
            }
        }

        subscript(dynamicMember key: String) -> Int? {
            get {
                if let result = key.withCString(getenv) {
                    return .init(String(cString: result))
                }
                return nil
            }
            set {
                key.withCString { _key in
                    guard let newValue else {
                        unsetenv(_key)
                        return
                    }
                    setenv(_key, String(newValue), 1)
                }
            }
        }

        subscript(dynamicMember key: String) -> Bool? {
            get {
                if let result = key.withCString(getenv) {
                    return .init(String(cString: result).lowercased())
                }
                return nil
            }
            set {
                key.withCString { _key in
                    guard let newValue else {
                        unsetenv(_key)
                        return
                    }
                    setenv(_key, newValue ? "True" : "False", 1)
                }
            }
        }
    }
}
"""


# ---------------------------------------------------------------------------
# Surface handoff
# ---------------------------------------------------------------------------


def _write_surface_swift(target_dir: Path) -> None:
    """The SurfaceView lifecycle, as seen from Swift.

    NucleantSurfaceView calls straight into these; they own the
    ``ANativeWindow*`` for the process and forward it to the renderer inside
    ``_nucleant.so``, which is what creates the ``VkSurfaceKHR``
    (``VK_KHR_android_surface``) and drives the render loop.

    That forward is a dlsym'd C ABI, not a Swift call: the wheel and this
    package are built by separate toolchain invocations with no link-time
    relationship, so no Swift type can cross between them.  It also means this
    package builds today, before anything on the other side exists — the hooks
    are simply absent and events are dropped with a log line.
    """
    content = """\
//
//  AndroidSurface.swift
//  Android surface lifecycle — generated by ksproject.
//
//  NucleantSurfaceView (Java) hands its android.view.Surface over as each
//  surface is created, resized, and destroyed.  The Surface arrives as a
//  swift-java `JavaObject`, from which ANativeWindow_fromSurface produces the
//  handle Vulkan wants — that call is the reason CAndroidNativeWindow exists.
//

import Android  // dlsym/dlfcn — Foundation does not re-export it on Android
import CAndroidNativeWindow
import Foundation
import SwiftJava

// MARK: - Host seam

// The renderer lives in `_nucleant.so` — the Nucleant wheel's extension module,
// which SwiftPM links the whole Nucleant graph into. That library and this one
// are built by separate toolchain invocations with no link-time relationship,
// so the seam between them cannot be a Swift protocol or any other Swift type:
// it has to be a C ABI resolved at runtime.
//
// Direction matters. The bootstrap is loaded first (System.loadLibrary, before
// Python starts) and `_nucleant.so` arrives later, when Python imports it — so
// the bootstrap looks *up*, lazily, rather than the wheel registering down into
// something that may not have been imported yet. `RTLD_DEFAULT` finds these
// once the extension module is loaded, whatever order that happens in.
//
// To receive events, the wheel exports any subset of:
//
//   @_cdecl("nucleant_android_surface_created")
//   func onSurfaceCreated(_ window: OpaquePointer?, _ w: Int32, _ h: Int32)
//   @_cdecl("nucleant_android_surface_resized")   (_ w: Int32, _ h: Int32)
//   @_cdecl("nucleant_android_surface_destroyed") ()
//   @_cdecl("nucleant_android_touch")   (_ phase: Int32, _ id: Int32, _ x: Float, _ y: Float)
//   @_cdecl("nucleant_android_key")     (_ down: Int32, _ code: Int32, _ unicode: Int32)
//   @_cdecl("nucleant_android_active")  (_ active: Int32)
//
// `window` is an `ANativeWindow *` — pass it straight to
// `VkAndroidSurfaceCreateInfoKHR.window`. It is valid until
// `nucleant_android_surface_destroyed` returns, and not one frame longer.

private typealias SurfaceCreatedFn = @convention(c) (OpaquePointer?, Int32, Int32) -> Void
private typealias SurfaceResizedFn = @convention(c) (Int32, Int32) -> Void
private typealias SurfaceDestroyedFn = @convention(c) () -> Void
private typealias TouchFn = @convention(c) (Int32, Int32, Float, Float) -> Void
private typealias KeyFn = @convention(c) (Int32, Int32, Int32) -> Void
private typealias ActiveFn = @convention(c) (Int32) -> Void

/// Touch phases passed as the first argument to `nucleant_android_touch`.
private enum TouchPhase: Int32 {
    case down = 0, moved = 1, up = 2, cancelled = 3
}

/// Looks up `name` in the process once and caches the result — including a
/// miss, so a wheel that exports only some of the hooks does not pay for a
/// failed dlsym on every touch event.
private nonisolated(unsafe) var symbolCache: [String: UnsafeMutableRawPointer?] = [:]
/// dlopen handle for the renderer library, once it has announced itself.
/// Guarded by `symbolLock` along with the cache.
private nonisolated(unsafe) var rendererHandle: UnsafeMutableRawPointer?
private let symbolLock = NSLock()

private func hostSymbol<T>(_ name: String, as type: T.Type) -> T? {
    symbolLock.lock()
    let cached: UnsafeMutableRawPointer??
    if let hit = symbolCache[name] {
        cached = .some(hit)
    } else {
        cached = nil
    }
    symbolLock.unlock()

    let raw: UnsafeMutableRawPointer?
    if let cached {
        raw = cached
    } else {
        // The renderer's handle before RTLD_DEFAULT, because RTLD_DEFAULT
        // cannot reach it: it searches the global group, and _nucleant.so is
        // dlopened by Python into its own linker namespace. The handle only
        // exists once the renderer has announced itself — see
        // nucleantRefreshHostHooks(_:).
        symbolLock.lock()
        let handle = rendererHandle
        symbolLock.unlock()

        var found = handle.flatMap { dlsym($0, name) }
        if found == nil {
            found = dlsym(UnsafeMutableRawPointer(bitPattern: 0), name)  // RTLD_DEFAULT
        }
        raw = found

        symbolLock.lock()
        symbolCache[name] = raw
        symbolLock.unlock()
        if raw == nil {
            NSLog("[nucleant] host hook \\(name) not exported — events dropped")
        }
    }
    guard let raw else { return nil }
    return unsafeBitCast(raw, to: type)
}

/// Drops every cached lookup. Call after loading a library that exports the
/// hooks if any event was already dispatched before it arrived — otherwise the
/// cached misses persist for the life of the process.
///
/// `@_cdecl` because the caller is the renderer, reaching back the same way
/// this file reaches it. Only the renderer knows when its own library finished
/// loading, and a mangled Swift symbol would make that lookup depend on this
/// module's name and signature.
///
/// `rendererPath` is that library's own filesystem path, which it can get from
/// `dladdr` on any of its own symbols. It is required rather than optional in
/// practice: `_nucleant.so` lives under site-packages, off the linker's search
/// path and in the namespace Python dlopened it into, so neither RTLD_DEFAULT
/// nor a dlopen by bare name can find it. Passing nil keeps the old
/// RTLD_DEFAULT-only behaviour.
@_cdecl("nucleant_refresh_host_hooks")
public func nucleantRefreshHostHooks(_ rendererPath: UnsafePointer<CChar>?) {
    symbolLock.lock()
    symbolCache.removeAll()
    if let rendererPath, rendererHandle == nil {
        // Already loaded, so this returns the existing handle rather than
        // mapping a second copy — it is the handle we are after, not the load.
        rendererHandle = dlopen(rendererPath, RTLD_NOW)
        if rendererHandle == nil {
            NSLog("[nucleant] could not open renderer at \\(String(cString: rendererPath))")
        }
    }
    symbolLock.unlock()

    // Replay the current surface: the renderer missed the original callback if
    // it loaded after the surface was created, which is the common case since
    // Python starts after the first frame's worth of lifecycle.
    windowLock.lock()
    let existing = nativeWindow
    windowLock.unlock()
    guard let existing,
          let fn = hostSymbol("nucleant_android_surface_created", as: SurfaceCreatedFn.self)
    else { return }
    fn(existing, ANativeWindow_getWidth(existing), ANativeWindow_getHeight(existing))
}

// MARK: - Window ownership

/// The window backing the on-screen surface, or nil between surfaceDestroyed
/// and the next surfaceCreated (app backgrounded, device rotated, and so on).
///
/// Written from the UI thread and read from the render thread, so every access
/// goes through the lock — a torn read here is a use-after-free of a window the
/// system has already reclaimed.
private nonisolated(unsafe) var nativeWindow: OpaquePointer?
private let windowLock = NSLock()

/// Broadcast every time a surface is created, so the launcher can wait for the
/// first one before running the app module — Android's equivalent of the iOS
/// launcher waiting on `scene(_:willConnectTo:)`.
private let surfaceSignal = NSCondition()

/// Blocks until a surface exists, up to `timeout`.  Returns false on timeout,
/// in which case the caller is expected to carry on and log it: an app that
/// never gets a surface is a bug to see, not a reason to hang forever.
///
/// Internal, not public: it takes a TimeInterval and is called from Swift only,
/// so there is nothing for jextract to export.
func nucleantAwaitSurface(timeout: TimeInterval) -> Bool {
    let deadline = Date().addingTimeInterval(timeout)
    surfaceSignal.lock()
    defer { surfaceSignal.unlock() }
    while true {
        windowLock.lock()
        let ready = nativeWindow != nil
        windowLock.unlock()
        if ready { return true }
        if !surfaceSignal.wait(until: deadline) { return false }
    }
}

/// The current ANativeWindow, retained for the caller's use.  Balance with
/// `nucleantReleaseWindow`.  Only needed by code that outlives a callback;
/// the host's `surfaceCreated(window:)` argument is already valid for the
/// surface's lifetime.
public func nucleantAcquireWindow() -> OpaquePointer? {
    windowLock.lock()
    defer { windowLock.unlock() }
    guard let window = nativeWindow else { return nil }
    ANativeWindow_acquire(window)
    return window
}

public func nucleantReleaseWindow(_ window: OpaquePointer?) {
    guard let window else { return }
    ANativeWindow_release(window)
}

// MARK: - First frame

/// Set by the renderer once it has presented a frame, read by the Activity so
/// it knows when to take the presplash down.
///
/// A flag polled from Java rather than a call up into Java: jextract generates
/// the Java -> Swift direction only, and reaching the Activity from the render
/// thread would mean a global ref plus AttachCurrentThread by hand. The
/// Activity is already on a looper, so letting it ask is far less machinery.
private nonisolated(unsafe) var firstFrameRendered = false
private let firstFrameLock = NSLock()

@_cdecl("nucleant_android_first_frame")
public func nucleantAndroidFirstFrame() {
    firstFrameLock.lock()
    firstFrameRendered = true
    firstFrameLock.unlock()
}

/// Whether a frame has reached the surface. Java-facing.
public func nucleantFirstFrameRendered() -> Bool {
    firstFrameLock.lock()
    defer { firstFrameLock.unlock() }
    return firstFrameRendered
}

// MARK: - Java-facing lifecycle

/// `SurfaceHolder.Callback.surfaceCreated`.
public func nucleantSurfaceCreated(surface: JavaObject) {
    // ANativeWindow_fromSurface takes the raw JNIEnv/jobject pair; swift-java
    // exposes both on every JavaObject, which is what keeps this from needing a
    // hand-written JNI entry point.
    guard let window = ANativeWindow_fromSurface(surface.javaEnvironment, surface.javaThis) else {
        NSLog("[nucleant] ERROR: ANativeWindow_fromSurface returned null")
        return
    }
    windowLock.lock()
    let previous = nativeWindow
    nativeWindow = window
    windowLock.unlock()
    if let previous { ANativeWindow_release(previous) }

    // Releases the launcher, which is parked in nucleantAwaitSurface waiting
    // for exactly this before it runs the app module.
    surfaceSignal.lock()
    surfaceSignal.broadcast()
    surfaceSignal.unlock()

    let width = ANativeWindow_getWidth(window)
    let height = ANativeWindow_getHeight(window)
    NSLog("[nucleant] surface created \\(width)x\\(height)")
    hostSymbol("nucleant_android_surface_created", as: SurfaceCreatedFn.self)?(
        window, width, height
    )
}

/// `SurfaceHolder.Callback.surfaceChanged` — rotation, resize, and the initial
/// size report that always follows surfaceCreated.
///
/// An Android app is always fullscreen, so this size is the window size, not a
/// request. It is the counterpart of iOS building its UIWindow from the scene:
/// whatever `WindowBase(x, y, w, h)` was constructed with is overridden here.
public func nucleantSurfaceChanged(width: Int32, height: Int32) {
    NSLog("[nucleant] surface changed \\(width)x\\(height)")
    hostSymbol("nucleant_android_surface_resized", as: SurfaceResizedFn.self)?(width, height)
}

/// `SurfaceHolder.Callback.surfaceDestroyed`.  Returns once the renderer has
/// stopped touching the window: the Surface is only guaranteed valid until
/// this call returns, so the view blocks on it.
public func nucleantSurfaceDestroyed() {
    hostSymbol("nucleant_android_surface_destroyed", as: SurfaceDestroyedFn.self)?()

    windowLock.lock()
    let window = nativeWindow
    nativeWindow = nil
    windowLock.unlock()
    if let window { ANativeWindow_release(window) }
    NSLog("[nucleant] surface destroyed")
}

// MARK: - Input

private func dispatchTouch(_ phase: TouchPhase, _ pointerId: Int32, _ x: Float, _ y: Float) {
    hostSymbol("nucleant_android_touch", as: TouchFn.self)?(phase.rawValue, pointerId, x, y)
}

public func nucleantTouchDown(pointerId: Int32, x: Float, y: Float) {
    dispatchTouch(.down, pointerId, x, y)
}

public func nucleantTouchMoved(pointerId: Int32, x: Float, y: Float) {
    dispatchTouch(.moved, pointerId, x, y)
}

public func nucleantTouchUp(pointerId: Int32, x: Float, y: Float) {
    dispatchTouch(.up, pointerId, x, y)
}

public func nucleantTouchCancelled(pointerId: Int32, x: Float, y: Float) {
    dispatchTouch(.cancelled, pointerId, x, y)
}

public func nucleantKeyDown(keyCode: Int32, unicodeChar: Int32) {
    hostSymbol("nucleant_android_key", as: KeyFn.self)?(1, keyCode, unicodeChar)
}

public func nucleantKeyUp(keyCode: Int32, unicodeChar: Int32) {
    hostSymbol("nucleant_android_key", as: KeyFn.self)?(0, keyCode, unicodeChar)
}

// MARK: - Activity lifecycle

public func nucleantOnResume() {
    hostSymbol("nucleant_android_active", as: ActiveFn.self)?(1)
}

public func nucleantOnPause() {
    hostSymbol("nucleant_android_active", as: ActiveFn.self)?(0)
}
"""
    (target_dir / "AndroidSurface.swift").write_text(content, encoding="utf-8")
